name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  gather-dependencies:
    runs-on: ubuntu-latest
    outputs:
      dd-trace-version: ${{ steps.dd-trace.outputs.version }}
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: Datadog.Trace version
        id: dd-trace
        run: echo ::set-output name=version::$(cat Project.csproj | grep Datadog.Trace | sed 's/.*Version="\([^"]*\).*/\1/i')
  build-image:
    needs: gather-dependencies
    env:
      # CR_UID: ${{ secrets.DOCKERHUB_USERNAME }}
      # CR_PWD: ${{ secrets.DOCKERHUB_TOKEN }}
      CR_UID: ${{ github.repository_owner }}
      CR_PWD: ${{ secrets.GITHUB_TOKEN }}
      CR_REG: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      DD_TRACE_VERSION: ${{needs.gather-dependencies.outputs.dd-trace-version}}
    runs-on: ubuntu-latest
    
    steps:
      - run: echo ${{ env.DD_TRACE_VERSION }}
#       - name: Dependabot metadata
#         if: ${{ github.actor == 'dependabot[bot]' }}
#         id: metadata
#         uses: dependabot/fetch-metadata@v1.1.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.CR_REG }}
          username: ${{ env.CR_UID }}
          password: ${{ env.CR_PWD }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          build-args: |
            DD_TRACE_VERSION=${{ env.DD_TRACE_VERSION }}
          push: true
          tags: |
            ${{ env.CR_REG }}/${{ env.IMAGE_NAME }}:LATEST
            ${{ env.CR_REG }}/${{ env.IMAGE_NAME }}:${{ env.DD_TRACE_VERSION }}
